name: Publish to Modrinth
on:
  release:
    types: [released]
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@4.2.2
        
      - name: Set up Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: "temurin"
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build the plugin
        run: ./gradlew clean build

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: voqEPXf8
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          game-versions: |
            >=1.21
          loaders: paper
          dependencies: packetevents@2.8.0(required)
